name: Deploy to AWS Lambda

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (prod)"
        required: true
        default: "prod"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    # env:
    #   MONGODB_URI: ${{ secrets.MONGODB_URI }}
    #   TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    #   OWNER_IDS: ${{ secrets.OWNER_IDS }}
    #   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    #   WEBHOOK_DOMAIN: ${{ secrets.WEBHOOK_DOMAIN }}
    #   WEBHOOK_SECRET_TOKEN: ${{ secrets.WEBHOOK_SECRET_TOKEN }}

    #   WEBHOOK_PATH: /api/webhook
    #   TELEGRAM_BOT_USERNAME: uncle_vova_ai_bot
    #   TELEGRAM_BOT_NAME: Дядя Вова
    #   PORT: 8080
    #   DEFAULT_MINUS_MINUTES: 20
    #   MESSAGES_LIMIT: 3
    #   EVERY_NTH_MESSAGE: 15
    #   MIN_MESSAGE_LENGTH: 20
    #   TEMPERATURE: 0.7
    #   MAX_TOKENS: 1000
    #   MODEL: gpt-4o

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip Lambda
        run: zip -r function.zip index.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --zip-file fileb://function.zip > /dev/null

      # - name: Update Lambda environment variables
      #   run: |
      #     aws lambda update-function-configuration \
      #       --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
      #       --environment '{"Variables": {
      #         "MONGODB_URI": "${{ secrets.MONGODB_URI }}",
      #         "TELEGRAM_BOT_TOKEN": "${{ secrets.TELEGRAM_BOT_TOKEN }}",
      #         "OWNER_IDS": "${{ secrets.OWNER_IDS }}",
      #         "OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}",
      #         "WEBHOOK_DOMAIN": "${{ secrets.WEBHOOK_DOMAIN }}",
      #         "WEBHOOK_SECRET_TOKEN": "${{ secrets.WEBHOOK_SECRET_TOKEN }}",
      #         "WEBHOOK_PATH": "/api/webhook",
      #         "TELEGRAM_BOT_USERNAME": "uncle_vova_ai_bot",
      #         "TELEGRAM_BOT_NAME": "Дядя Вова",
      #         "PORT": "8080",
      #         "DEFAULT_MINUS_MINUTES": "20",
      #         "MESSAGES_LIMIT": "3",
      #         "EVERY_NTH_MESSAGE": "15",
      #         "MIN_MESSAGE_LENGTH": "20",
      #         "TEMPERATURE": "0.7",
      #         "MAX_TOKENS": "1000",
      #         "MODEL": "gpt-4o"
      #       }}'
